services:
  # Trạm 1: Database Local (Dùng thay Azure khi offline)
  db:
    image: mysql:8.0
    container_name: afes-db
    environment:
      MYSQL_DATABASE: afes_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3307:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 10

  # Trạm 2: MQTT Broker (Trạm trung chuyển dữ liệu)
  mosquitto:
    build:
      context: ./mqtt/mqtt      # Trỏ vào thư mục chứa Dockerfile (Lớp 2)
      dockerfile: Dockerfile
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      # Data và log nằm ngang hàng Dockerfile nên chỉ cần 2 chữ mqtt
      - ./mqtt/mqtt/data:/mosquitto/data
      - ./mqtt/mqtt/log:/mosquitto/log
  # Trạm 3: Backend Spring Boot
  backend:
    build: ./backend
    container_name: afes-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/afes_db?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=password
      # QUAN TRỌNG: Cấp địa chỉ để Backend biết đường tìm MQTT Broker trong mạng Docker
      - MQTT_BROKER_URL=tcp://mosquitto:1883
    depends_on:
      db:
        condition: service_healthy
      # Backend cũng phải chờ MQTT chạy lên thì mới khởi động được
      mosquitto:
        condition: service_started

  # IF USE AZURE (Đã căn chỉnh lại dấu cách cho đẹp)
  # backend:
  #   build: ./backend
  #   container_name: afes-backend
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:mysql://afes-db.mysql.database.azure.com:3306/afes_db?useSSL=true
  #     - SPRING_DATASOURCE_USERNAME=admin123
  #     - SPRING_DATASOURCE_PASSWORD=Hello123
  #     - MQTT_BROKER_URL=tcp://mosquitto:1883

  # Trạm 4: Frontend
  frontend:
    build: ./frontend
    container_name: afes-frontend
    ports:
      - "80:80"
    depends_on:
      - backend